export type IImageUpload = {
    alternativeTex: 'string'
    caption: 'string'
    createdAt: 'string'
    ext: 'string'
    formats: 'string'
    hash: 'string'
    height: 'string'
    id: 'string'
    mime: 'string'
    name: 'string'
    previewUrl: 'string'
    provider: 'string'
    provider_metadata: 'string'
    size: 'string'
    updatedAt: 'string'
    url: 'string'
    width: 'string'
}
